# 3. Introduction to numpy


**Instructions:**
* go through the notebook and complete the **tasks** .  
* Make sure you understand the examples given!
* ** Save your notebooks when you are done! **

Note that we use the import keyword to import modules and libraries in Python (more <a href="https://docs.python.org/3/tutorial/modules.html">here</a>)

See details on documentation / resources here:
https://learn.gold.ac.uk/mod/page/view.php?id=487982

In [1]:
import numpy as np

## 3.2 Numpy Arrays
Numpy ndarrays are a fundamental structure for ML in python.


### 3.2.1 Usage Examples

** Create numpy array from list **

    data1D = [6, 7, 8]
    data1DnD = np.array(data1D)
    print(data1D)
    print(data1DnD)
   

** print useful properties of our array **

    print(data1DnD.shape)
    print(data1DnD.ndim)
    print(data1DnD.dtype)
    
    
** change type of elements **

    data1DnD_float = data1DnD.astype(np.float)
    data1DnD_string = data1DnD.astype(np.string_)
   
    
** array indexing **

    print(a[0])   #return the first element of ndarray a
    print(a[:])   #return all the elements of ndarray a
    print(a[-1])  #return the last element of ndarray a
    print(a[:-1]) #return everything up to the last element
    print(a[:-2]) #return everything up to the second last element
    print(a[-2])  #return the second last element

** various ways of creating an ndarray **

    a = np.array([1, 2, 3])
    b = np.zeros((1,5))              # Create an array of all zeros
    c = np.ones((1,5))               # Create an array of all ones
    d = np.full((1,5), 7)            # Create an array filled with value 7
    e = np.random.random((1,4))      # Create an array filled with random values
    f = np.eye(3)                    # Create a 3x3 identity matrix (2D array)
    g = np.ones((3,3,3))             # 3-Dimensional array
    
** generalization to n-dimensional arrays **

    A=np.array([ [1,2], [3,4] ])     # Create a 2-D array (Matrix)
    print(A[0,1])                    # return the element on first column, second row (0,1)=2
                                     # array indexing works as above
    

** reshaping **

    We can reshape a vector (e.g., v=[v1,v2,...vN]) to a matrix of N1, N2 dimensions (where N1xN2 = N)
    This is very useful for plotting images.  For 2 dimensions, the related numpy method is np.reshape(ndarray, [dim1, dim2])
<hr>

<span style="color:rgb(170,0,0)">**Task:**</span>
- Go through the examples above, pasting the code given in the empty cell below and verifying the results.  
- Make sure you understand what this basic code does (numpy documentation <a href="http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html">here</a>)

In [10]:
#Code here

## Create numpy array from list
data1D = [6, 7, 8]
data1DnD = np.array(data1D)
print(data1D)
print(data1DnD)

print("---------------")

## print useful properties of our array
print(data1DnD.shape)
print(data1DnD.ndim)
print(data1DnD.dtype)

print("---------------")

## change type of elements
data1DnD_float = data1DnD.astype(np.float)
print(data1DnD_float)
data1DnD_string = data1DnD.astype(np.string_)
print(data1DnD_string)

print("---------------")

aa = data1DnD

## array indexing
print(aa[0])   #return the first element of ndarray aa
print(aa[:])   #return all the elements of ndarray aa
print(aa[-1])  #return the last element of ndarray aa
print(aa[:-1]) #return everything up to the last element
print(aa[:-2]) #return everything up to the second last element
print(aa[-2])  #return the second last element

print("---------------")

## various ways of creating an ndarray
a = np.array([1, 2, 3])
b = np.zeros((1,5))              # Create an array of all zeros
c = np.ones((1,5))               # Create an array of all ones
d = np.full((1,5), 7)            # Create an array filled with value 7
e = np.random.random((1,4))      # Create an array filled with random values
f = np.eye(3)                    # Create a 3x3 identity matrix (2D array)
g = np.ones((3,3,3))             # 3-Dimensional array

print(a,b,c,d,e,f,g)

print("---------------")

## generalization to n-dimensional arrays
A=np.array([ [1,2], [3,4] ])     # Create a 2-D array (Matrix)
print(A[0,1])                    # return the element on first column, second row (0,1)=2
                                 # array indexing works as above
    
print("---------------")

## reshaping
#We can reshape a vector (e.g., v=[v1,v2,...vN]) to a matrix of N1, N2 dimensions (where N1xN2 = N)
#This is very useful for plotting images.  For 2 dimensions, the related numpy method is np.reshape(ndarray, [dim1, dim2])

ndarray = np.random.random(100)
np.reshape(ndarray, [10, 10])
print(ndarray)

print("************")

[6, 7, 8]
[6 7 8]
---------------
(3,)
1
int64
---------------
[ 6.  7.  8.]
[b'6' b'7' b'8']
---------------
6
[6 7 8]
8
[6 7]
[6]
7
---------------
[1 2 3] [[ 0.  0.  0.  0.  0.]] [[ 1.  1.  1.  1.  1.]] [[7 7 7 7 7]] [[ 0.4678367   0.7169802   0.147179    0.71499601]] [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]] [[[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]]
---------------
2
---------------
[ 0.28797266  0.62464361  0.76718415  0.86645944  0.89003341  0.71749639
  0.79743375  0.11626203  0.45178951  0.4556574   0.72407729  0.16139165
  0.46295611  0.01170855  0.37899714  0.21305345  0.86479215  0.91662401
  0.9118719   0.64784037  0.60468367  0.67674512  0.6633462   0.39601113
  0.22453908  0.68566172  0.26662366  0.67409559  0.83090925  0.47478183
  0.44368899  0.72975811  0.86917158  0.69787221  0.93422462  0.32269883
  0.10019229  0.19353053  0.59289477  0.71433336  0.64730972

<span style="color:rgb(170,0,0)">**Task:**</span> In the empty cell below,  create an np array called L consisting of 15 random elements

In [4]:
#Code here

L = np.random.random((15))      # Create an array filled with random values
print(L)


[ 0.81150068  0.35302769  0.76031847  0.52433677  0.39411848  0.52680883
  0.35174292  0.69392866  0.37530316  0.06827655  0.13078352  0.81880463
  0.60893564  0.5524553   0.75054823]


<span style="color:rgb(170,0,0)">**Task:**</span> Reshape the array L to a matrix A that has 5 rows and 3 columns.  Print the matrix to verify the result.

In [15]:
#Code here

A = np.reshape(L, [5,3])
print(A)
print("--------")

A1 = L.reshape(5,3)
print(L)
print(A1)

[[ 0.81150068  0.35302769  0.76031847]
 [ 0.52433677  0.39411848  0.52680883]
 [ 0.35174292  0.69392866  0.37530316]
 [ 0.06827655  0.13078352  0.81880463]
 [ 0.60893564  0.5524553   0.75054823]]
--------
[ 0.81150068  0.35302769  0.76031847  0.52433677  0.39411848  0.52680883
  0.35174292  0.69392866  0.37530316  0.06827655  0.13078352  0.81880463
  0.60893564  0.5524553   0.75054823]
[[ 0.81150068  0.35302769  0.76031847]
 [ 0.52433677  0.39411848  0.52680883]
 [ 0.35174292  0.69392866  0.37530316]
 [ 0.06827655  0.13078352  0.81880463]
 [ 0.60893564  0.5524553   0.75054823]]


<span style="color:rgb(170,0,0)">**Task:**</span> Reshape matrix A to a matrix B that has 3 rows and 5 columns.  Then, print the elements in row 0 and 1 only.

In [20]:
#Code here
B = A.reshape(3,5)
for i in range (0, 2):
    print(B[i])

[ 0.81150068  0.35302769  0.76031847  0.52433677  0.39411848]
[ 0.52680883  0.35174292  0.69392866  0.37530316  0.06827655]


<span style="color:rgb(170,0,0)">**Task:**</span> Print all elements of B that are in row 0 and 2 **and** column 1 ( intersection 'AND' )

In [23]:
#Code here

print(B[0,1], B[2,1])


0.353027685512 0.818804629238


<span style="color:rgb(170,0,0)">**Task:**</span> Print all elements of A that are in the last row (see the [-1] notation above) and second to last column.  

--That is, the INTERSECTION between the last row and the 2nd last column

In [34]:
#Code here

print(A[[-1],[-2]])

[ 0.5524553]


<span style="color:rgb(170,0,0)">**Task:**</span> Given the array Y below, find all **indices** in the array that are equal to the value 1.  Use the numpy function ``where`` to do that . Your final output should look like this: ``[1, 3, 4, 7]``.

documentation: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.where.html

In [38]:
Y=np.array([0, 1, 0, 1,1, 2,0,1,0])
#Code here

print(np.where(Y==1))

(array([1, 3, 4, 7]),)


<span style="color:rgb(170,0,0)">**Task:**</span> Split the array Y defined above into three arrays by using the numpy function ``array_split``.  Print to verify.

Documentation: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.array_split.html. 

In [41]:
#Code here

print(np.array_split(Y, 3))
print(Y)

[array([0, 1, 0]), array([1, 1, 2]), array([0, 1, 0])]
[0 1 0 1 1 2 0 1 0]


<span style="color:rgb(170,0,0)">**Task:**</span> Given the array D defined below, find the **indices** that sort the array.  Use the numpy function ``argsort`` in order to do so.  Subsequently, print the sorted array.  Final output should look like this:
``
[ 0  1  2  5  9 10 20]
``

In [62]:
D=np.array([10,5,2,9,20,0,1])
#Code here

sorted_arg = np.argsort(D)
sorted_a = np.zeros(len(D))

for i in range (0, len(D)):
    sorted_a[i] = D[sorted_arg[i]]

print(sorted_a)

[  0.   1.   2.   5.   9.  10.  20.]


<span style="color:rgb(170,0,0)">**Task:**</span> Create two random 2x2 matrices X and Y (2 rows, 2 columns).  Use the numpy function ``concatenate`` in order to concatenate them and create a matrix Z that has dimensions 4x2 and a matrix W that has dimensions 2x4

documentation: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.concatenate.html

In [ ]:
#Code here


<span style="color:rgb(170,0,0)">**Task:**</span> Create the same matrices Z2=Z and W2=W (where Z and W are as defined above), but this time use the numpy functions ``hstack`` and ``vstack``

Documentation:

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.hstack.html#numpy.hstack

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.vstack.html#numpy.vstack

In [ ]:
#Code here